package com.zzq.dataobject;

public class BookStockDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_stock.id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_stock.stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_stock.book_id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private Integer bookId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_stock.id
     *
     * @return the value of book_stock.id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_stock.id
     *
     * @param id the value for book_stock.id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_stock.stock
     *
     * @return the value of book_stock.stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_stock.stock
     *
     * @param stock the value for book_stock.stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_stock.book_id
     *
     * @return the value of book_stock.book_id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_stock.book_id
     *
     * @param bookId the value for book_stock.book_id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }
}