package com.zzq.dataobject;

public class BookDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.title
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.auther
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private String auther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.press
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private String press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.price
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.description
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.sales
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.img_url
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.id
     *
     * @return the value of book.id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.id
     *
     * @param id the value for book.id
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.title
     *
     * @return the value of book.title
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.title
     *
     * @param title the value for book.title
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.auther
     *
     * @return the value of book.auther
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public String getAuther() {
        return auther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.auther
     *
     * @param auther the value for book.auther
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setAuther(String auther) {
        this.auther = auther == null ? null : auther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.press
     *
     * @return the value of book.press
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public String getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.press
     *
     * @param press the value for book.press
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setPress(String press) {
        this.press = press == null ? null : press.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.price
     *
     * @return the value of book.price
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.price
     *
     * @param price the value for book.price
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.description
     *
     * @return the value of book.description
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.description
     *
     * @param description the value for book.description
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.sales
     *
     * @return the value of book.sales
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.sales
     *
     * @param sales the value for book.sales
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.img_url
     *
     * @return the value of book.img_url
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.img_url
     *
     * @param imgUrl the value for book.img_url
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}