package com.zzq.dataobject;

public class CheckDetailDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.user_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.item_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.item_price
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private Double itemPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.amount
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.order_price
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private Double orderPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_detail.info_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    private Integer infoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.id
     *
     * @return the value of check_detail.id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.id
     *
     * @param id the value for check_detail.id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.user_id
     *
     * @return the value of check_detail.user_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.user_id
     *
     * @param userId the value for check_detail.user_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.item_id
     *
     * @return the value of check_detail.item_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.item_id
     *
     * @param itemId the value for check_detail.item_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.item_price
     *
     * @return the value of check_detail.item_price
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public Double getItemPrice() {
        return itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.item_price
     *
     * @param itemPrice the value for check_detail.item_price
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setItemPrice(Double itemPrice) {
        this.itemPrice = itemPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.amount
     *
     * @return the value of check_detail.amount
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.amount
     *
     * @param amount the value for check_detail.amount
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.order_price
     *
     * @return the value of check_detail.order_price
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public Double getOrderPrice() {
        return orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.order_price
     *
     * @param orderPrice the value for check_detail.order_price
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setOrderPrice(Double orderPrice) {
        this.orderPrice = orderPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_detail.info_id
     *
     * @return the value of check_detail.info_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public Integer getInfoId() {
        return infoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_detail.info_id
     *
     * @param infoId the value for check_detail.info_id
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    public void setInfoId(Integer infoId) {
        this.infoId = infoId;
    }
}