package com.zzq.dataobject;

public class CheckDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_info.id
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_info.user_id
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_info.address
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column check_info.price
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    private Double price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_info.id
     *
     * @return the value of check_info.id
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_info.id
     *
     * @param id the value for check_info.id
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_info.user_id
     *
     * @return the value of check_info.user_id
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_info.user_id
     *
     * @param userId the value for check_info.user_id
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_info.address
     *
     * @return the value of check_info.address
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_info.address
     *
     * @param address the value for check_info.address
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column check_info.price
     *
     * @return the value of check_info.price
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column check_info.price
     *
     * @param price the value for check_info.price
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }
}