package com.zzq.dataobject;

public class ItemStockDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.id
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.sotck
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column item_stock.item_id
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    private Integer itemId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.id
     *
     * @return the value of item_stock.id
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.id
     *
     * @param id the value for item_stock.id
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.sotck
     *
     * @return the value of item_stock.sotck
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    public Integer getSotck() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.sotck
     *
     * @param stock the value for item_stock.sotck
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    public void setSotck(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column item_stock.item_id
     *
     * @return the value of item_stock.item_id
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column item_stock.item_id
     *
     * @param itemId the value for item_stock.item_id
     *
     * @mbg.generated Fri Mar 29 15:55:19 CST 2019
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }
}