package com.zzq.dao;

import com.zzq.dataobject.AdminDo;

public interface AdminDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated Sat Apr 27 11:16:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated Sat Apr 27 11:16:39 CST 2019
     */
    int insert(AdminDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated Sat Apr 27 11:16:39 CST 2019
     */
    int insertSelective(AdminDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated Sat Apr 27 11:16:39 CST 2019
     */
    AdminDo selectByPrimaryKey(Integer id);
    AdminDo selectByUserName(String username);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated Sat Apr 27 11:16:39 CST 2019
     */
    int updateByPrimaryKeySelective(AdminDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user
     *
     * @mbg.generated Sat Apr 27 11:16:39 CST 2019
     */
    int updateByPrimaryKey(AdminDo record);
}