package com.zzq.dao;

import com.zzq.dataobject.BookDo;

public interface BookDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int insert(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int insertSelective(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    BookDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int updateByPrimaryKeySelective(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int updateByPrimaryKey(BookDo record);
}