package com.zzq.dao;

import com.zzq.dataobject.BookStockDo;

public interface BookStockDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int insert(BookStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int insertSelective(BookStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    BookStockDo selectByPrimaryKey(Integer id);
    BookStockDo selectByBookId(Integer bookId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int updateByPrimaryKeySelective(BookStockDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_stock
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int updateByPrimaryKey(BookStockDo record);
}