package com.zzq.dao;

import com.zzq.dataobject.BookDo;
import com.zzq.service.model.BookModel;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BookDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    List<BookDo> listBook();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int insert(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int insertSelective(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    BookDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int updateByPrimaryKeySelective(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Wed Apr 10 14:06:20 CST 2019
     */
    int updateByPrimaryKey(BookDo record);
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
}