package com.zzq.dao;

import com.zzq.dataobject.BookDo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BookDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Apr 15 16:32:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Apr 15 16:32:47 CST 2019
     */
    int insert(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Apr 15 16:32:47 CST 2019
     */
    int insertSelective(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Apr 15 16:32:47 CST 2019
     */
    BookDo selectByPrimaryKey(Integer id);

    BookDo selectByTitle(String title);
    List<BookDo> selectByAuther(String auther);
    List<BookDo> selectByCategory(String category);
    List<BookDo> selectByKeyword(String keyword);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Apr 15 16:32:47 CST 2019
     */
    int updateByPrimaryKeySelective(BookDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book
     *
     * @mbg.generated Mon Apr 15 16:32:47 CST 2019
     */
    int updateByPrimaryKey(BookDo record);
    int increaseSales(@Param("id") Integer id, @Param("amount") Integer amount);
    List<BookDo> listBook();
}