package com.zzq.dao;

import com.zzq.dataobject.CheckDo;

public interface CheckDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    int insert(CheckDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    int insertSelective(CheckDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    CheckDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    int updateByPrimaryKeySelective(CheckDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_info
     *
     * @mbg.generated Fri Apr 26 18:07:58 CST 2019
     */
    int updateByPrimaryKey(CheckDo record);
}