package com.zzq.dao;

import com.zzq.dataobject.CheckDetailDo;

public interface CheckDetailDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Fri Apr 26 19:12:58 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Fri Apr 26 19:12:58 CST 2019
     */
    int insert(CheckDetailDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Fri Apr 26 19:12:58 CST 2019
     */
    int insertSelective(CheckDetailDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Fri Apr 26 19:12:58 CST 2019
     */
    CheckDetailDo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Fri Apr 26 19:12:58 CST 2019
     */
    int updateByPrimaryKeySelective(CheckDetailDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Fri Apr 26 19:12:58 CST 2019
     */
    int updateByPrimaryKey(CheckDetailDo record);
}