package com.zzq.dao;

import com.zzq.dataobject.CheckDetailDo;

public interface CheckDetailDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    int insert(CheckDetailDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table check_detail
     *
     * @mbg.generated Mon Apr 29 17:57:14 CST 2019
     */
    int insertSelective(CheckDetailDo record);
}